apiVersion: v1
kind: Secret
metadata:
  name: inventory-secrets
  labels:
    {{- include "inventory.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresPassword | quote }}
  bus-token: {{ .Values.busToken | quote }}
  admin-email: {{ .Values.adminEmail | quote }}
  admin-password: {{ .Values.adminPassword | quote }}
